language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_install: npm install -g grunt-cli
script: npm test
after_script: NODE_ENV=test npm install coveralls mocha-lcov-reporter && ./node_modules/.bin/istanbul
  cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info
  | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
before_deploy:
- grunt
- ls -A | grep -v "dist" | xargs rm -rf
- cp -r dist/* .
- rm -rf dist/
deploy:
  provider: npm
  email: mugo@forfuture.co.ke
  on:
    branch: master
    tags: true
  skip_cleanup: true
  api_key:
    secure: Yep+UnYxHBi6SKAjwEj1hIK1rV/fp8Y5nxi/Y1x+ZxpuyE29qJux1FkJUSAa6uIhIwW+qUWsXnwzsao7HYFlGPg7hV6GCnARpsLv3TbIVbNeJiq4SXfUAQxeUUKlhKaHOWq1emGM18aHFSYTZ9JKZzJ6n1P8lhaqrJy417lF7TQ=
